name: bloc_counter_app
description: "Flutter Bloc States Management Counter App"


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.0







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
